spring:
  application:
    name: "keyduck"

  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=6h

  config:
    import: optional:file:.env.properties

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create

  datasource:
    # 기본은 RDS (Production 환경)
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DATABASE}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 테스트 환경에서는 H2 사용
  profiles:
    group:
      test: h2

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

payment:
  toss:
    test-client-api-key: ${PAYMENT_CLIENT_API_KEY}
    test-secret-api-key: ${PAYMENT_SECRET_API_KEY}
    payment-url: ${PAYMENT_URL}