spring:
  application:
    name: "keyduck"

  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=6h

  config:
    import: optional:file:.env.properties

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false

    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DATABASE}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

payment:
  toss:
    test-client-api-key: ${PAYMENT_CLIENT_API_KEY}
    test-secret-api-key: ${PAYMENT_SECRET_API_KEY}
    payment-url: ${PAYMENT_URL}
