name: Deploy

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #      - name: Set up JDK
      #        uses: actions/setup-java@v2
      #        with:
      #          java-version: '17'

      - name: Gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: Linux-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            Linux-gradle-

      - name: Make .env file from GitHub Secrets
        run: |
          echo "${{ secrets.ENV_SECRET }}" > .env
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build the application and Docker image
        run: |
          ./gradlew bootJar -x test
          docker build -t myapp:latest .

      - name: Save Docker image
        run: docker save myapp:latest | gzip > myapp.tar.gz

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: |
            .env
            myapp.tar.gz
            ./build/libs/*.jar
          target: "~"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop myapp-container || true
            docker rm myapp-container || true
            docker load < myapp.tar.gz
            docker run -d --name myapp-container --env-file .env -p 8080:8080 myapp:latest
            docker image prune -f