name: Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: Linux-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            Linux-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run tests with H2
        run: ./gradlew test -Dspring.profiles.active=test