#name: Run Tests on PR
#
#on:
#  pull_request:
#    branches:
#      - test/git-action-ci-cd
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      #      - name: Set up JDK
#      #        uses: actions/setup-java@v2
#      #        with:
#      #          java-version: '17'
#
#      - name: Gradle 캐싱
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: Linux-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            Linux-gradle-
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./gradlew
#
#      - name: Run tests
#        run: ./gradlew test